// drill-library.js — Drill library for Practice Planner v2
// Research-backed drill library — max participation, no 1v1 drills
// Last updated: 2026-03-18
// KEY PRINCIPLE: Every drill = ALL 9 players active simultaneously. Zero line-standing.

export const DRILL_CATEGORIES = {
  warmup:    { emoji: '🏃', label: 'Warm-Up',        color: '#22c55e' },
  evasion:   { emoji: '💨', label: 'Evasion',        color: '#f59e0b' },
  defense:   { emoji: '🛡️', label: 'Defense',        color: '#ef4444' },
  receiving: { emoji: '🙌', label: 'Receiving',      color: '#3b82f6' },
  throwing:  { emoji: '🎯', label: 'Throwing',       color: '#8b5cf6' },
  handoffs:  { emoji: '🤝', label: 'Handoffs',       color: '#ec4899' },
  routes:    { emoji: '📐', label: 'Route Running',  color: '#06b6d4' },
  team:      { emoji: '🏈', label: 'Team',           color: '#14b8a6' },
  scrimmage: { emoji: '🏟️', label: 'Scrimmage',      color: '#f97316' },
}

export const DRILL_LIBRARY = [
  // ── WARMUP ──────────────────────────────────────────────────────────────
  {
    id: 'dynamic-warmup',
    name: 'Dynamic Warm-Up',
    category: 'warmup',
    duration: 7,
    description: 'Full movement prep: high knees, butt kicks, shuffles, sprints, flag-specific buzzes. ALL players go at once across the width.',
    setup: 'Line up on sideline, go across and back (10-15 yards). All 9 kids go simultaneously — nobody waits.',
    coachingPoints: [
      'We warm up like pros — no walking!',
      'Buzz feet = short choppy steps, stay low',
      'Sequence: high knees → butt kicks → Frankensteins → backpedal → side shuffle left → side shuffle right → sprint',
      'On the sprint, RACE — first one wins bragging rights',
    ],
    playerCount: { min: 1, ideal: 10 },
    equipment: [],
    difficulty: 1,
    isCustom: false,
  },
  {
    id: 'defensive-shuffle',
    name: 'Defensive Shuffle',
    category: 'warmup',
    duration: 3,
    description: 'Side step shuffling with arms wide — defense positioning muscle memory. All players go simultaneously.',
    setup: 'Line up on the sideline facing the field. Arms out wide — full wingspan. All go at same time.',
    coachingPoints: [
      'Stay low in athletic stance, knees bent',
      'Keep arms wide the ENTIRE time',
      'Never cross your feet — shuffle step only',
      'This is your defensive coverage zone width',
    ],
    playerCount: { min: 1, ideal: 10 },
    equipment: [],
    difficulty: 1,
    isCustom: false,
  },
  {
    id: 'diamond-catch-high',
    name: 'Diamond Catch Circles (High)',
    category: 'warmup',
    duration: 2,
    description: 'Arm circles with diamond hand shape — teaches high catch technique. All players do it simultaneously.',
    setup: 'Stand with feet shoulder width apart. Make diamond with thumbs + index fingers touching. ALL go at once.',
    coachingPoints: [
      'Diamond hands (thumbs together) for any ball ABOVE the chest',
      '10 circles forward, 10 circles backward',
      "Watch the diamond window — that's where the ball goes",
      'Squeeze at the end — hands are your gloves',
    ],
    playerCount: { min: 1, ideal: 10 },
    equipment: [],
    difficulty: 1,
    isCustom: false,
  },
  {
    id: 'pinky-catch-low',
    name: 'Pinky Catch Circles (Low)',
    category: 'warmup',
    duration: 2,
    description: 'Arm circles with pinkies crossed — teaches low catch technique. All players simultaneously.',
    setup: 'Stand with feet shoulder width apart. Cross pinky fingers, palms facing up (basket shape). All go at once.',
    coachingPoints: [
      'Pinkies together for any ball BELOW the chest',
      '10 circles forward, 10 circles backward',
      "Watch the basket as it moves — that's where you scoop low balls",
      'Low balls are the hardest — practice them most',
    ],
    playerCount: { min: 1, ideal: 10 },
    equipment: [],
    difficulty: 1,
    isCustom: false,
  },
  {
    id: 'tag-n-go',
    name: 'Tag & Go (Flag Warm-Up)',
    category: 'warmup',
    duration: 4,
    description: 'All players on, everyone tries to pull everyone else\'s flags while protecting their own. Pure chaos warm-up.',
    setup: '20×20 yard box. All 9 kids have flags on. On GO — pull flags, protect yours. If you lose both flags you\'re still in but count your pulls.',
    coachingPoints: [
      'Eyes UP — see the whole field, not just one target',
      'Reach for the hip, not the flag tape — grab from the belt',
      'Keep moving — standing still = easy target',
      'Count your successful pulls — compete against yourself',
    ],
    playerCount: { min: 5, ideal: 9 },
    equipment: ['cones', 'flags'],
    difficulty: 1,
    isCustom: false,
  },

  // ── EVASION ──────────────────────────────────────────────────────────────
  {
    id: 'mirror-dodge',
    name: '4v4 Mirror Dodge',
    category: 'evasion',
    jukeRelated: ['cut-juke', 'drop', 'shimmy'],
    duration: 5,
    description: '4 pairs face each other simultaneously — ball carrier jukes, defender mirrors. All 8 players moving at once, coach watches all.',
    setup: '4 pairs face each other 3 yards apart. Use cones to mark 5-yard lanes. ALL 4 pairs go simultaneously on coach\'s signal. Swap roles every 30 sec.',
    coachingPoints: [
      'Ball carrier: juke BOTH directions — show them you can go either way',
      'Defender: watch the HIPS not the eyes, hips tell truth',
      'Switch every 30 seconds so everyone defends and attacks',
      'Watch for kids who only juke one direction — call them out',
    ],
    playerCount: { min: 2, ideal: 8 },
    equipment: ['cones'],
    difficulty: 1,
    isCustom: false,
  },
  {
    id: 'gauntlet-run',
    name: 'Double Gauntlet Run',
    category: 'evasion',
    jukeRelated: ['cut-juke', 'drop', 'get-skinny', 'speed-change', 'shimmy', 'spin'],
    duration: 8,
    description: 'TWO parallel gauntlets running simultaneously — 4 defenders per gauntlet, runner chains juke moves past each. Zero waiting.',
    setup: '4 cones in a line, 5 yards apart = one gauntlet. Set up TWO parallel gauntlets 10 yards apart. 1 defender at each cone (confined to 3-yard box). Both runners go simultaneously.',
    coachingPoints: [
      "Don't use a move if you can just outrun them — moves cost speed",
      'Chain moves: read the NEXT defender before you finish the current one',
      'After each run, runner replaces the last defender, everyone shifts up one',
      'Both gauntlets race — adds competitive pressure',
    ],
    playerCount: { min: 5, ideal: 10 },
    equipment: ['cones'],
    difficulty: 2,
    isCustom: false,
  },
  {
    id: 'group-open-field',
    name: 'Group Open Field (4v4 Simultaneous)',
    category: 'evasion',
    jukeRelated: ['cut-juke', 'drop', 'shimmy', 'spin'],
    duration: 5,
    description: '4 pairs run simultaneously in separate 10×10 boxes — ball carrier vs flag puller. No waiting in line. Classic 1v1 redesigned for 100% participation.',
    setup: 'Mark 4 separate 10×10 boxes using cones. 1 ball carrier + 1 defender per box. All 4 pairs go on coach\'s signal. Rotate roles every rep. 9th kid rotates into a box each rep.',
    coachingPoints: [
      'Attack space, not the defender — go around, not through',
      'Defender: Eyes → Buzz feet → Rip the flag (3-step process)',
      'After each rep, ball carrier and defender swap immediately',
      'Winner of each box does a victory juke dance — keeps it fun',
    ],
    playerCount: { min: 4, ideal: 9 },
    equipment: ['cones'],
    difficulty: 2,
    isCustom: false,
  },
  {
    id: 'cone-weave-relay',
    name: 'Cone Weave Relay',
    category: 'evasion',
    jukeRelated: ['cut-juke', 'get-skinny'],
    duration: 5,
    description: 'TWO relay teams run simultaneously — weave through cones, dodge a live flag puller, sprint home.',
    setup: 'Two teams of 4-5. Each team has 5 zig-zag cones + one flag puller at the end. Both teams race simultaneously. Flag puller rotates every 2 runners.',
    coachingPoints: [
      'Must touch each cone — shortcuts = redo',
      'Flag puller rotates every 2 runners so everyone gets reps',
      'Teaches cutting + finishing when tired (4th quarter legs)',
      'Losing team does 5 jumping jacks — keeps stakes alive',
    ],
    playerCount: { min: 6, ideal: 10 },
    equipment: ['cones'],
    difficulty: 1,
    isCustom: false,
  },
  {
    id: 'juke-relay',
    name: 'Juke Relay',
    category: 'evasion',
    jukeRelated: ['cut-juke', 'drop', 'shimmy', 'spin'],
    duration: 5,
    description: 'Two teams race through juke stations — each cone requires a specific move. Competition drives intensity.',
    setup: 'Two parallel relay courses. 4 cone stations per course: station 1=cut, 2=drop, 3=shimmy, 4=spin. Coach calls each move as runners approach. Both teams go simultaneously.',
    coachingPoints: [
      'Call out which move at each station before they reach it',
      'Must execute the move or they redo that cone',
      'Team competition keeps energy high — don\'t let them sleepwalk through',
      'Rotate which move goes at which station each round',
    ],
    playerCount: { min: 4, ideal: 10 },
    equipment: ['cones'],
    difficulty: 2,
    isCustom: false,
  },
  {
    id: 'follow-the-leader',
    name: 'Follow the Leader',
    category: 'evasion',
    jukeRelated: ['cut-juke', 'drop', 'speed-change'],
    duration: 5,
    description: 'Leader runs at 70%, others mimic cuts and moves in a chain. All 9 players moving the whole time.',
    setup: 'Single file line, 2 yards between each player. Leader runs at 70% speed making sharp cuts and juke moves in open space.',
    coachingPoints: [
      'Rotate leaders every 60 seconds — put your fastest kid in the MIDDLE',
      "Keep spacing — don't bunch up or you can't mirror the cuts",
      'Teaches reading body language and reactive cutting — key for route running too',
      'Leader: make it HARD — don\'t just jog in a straight line',
    ],
    playerCount: { min: 3, ideal: 9 },
    equipment: [],
    difficulty: 1,
    isCustom: false,
  },
  {
    id: 'sharks-and-minnows',
    name: 'Sharks & Minnows',
    category: 'evasion',
    jukeRelated: ['cut-juke', 'drop', 'shimmy', 'spin'],
    duration: 8,
    description: 'Flag pulling + juke practice in a confined box. ALL players active — sharks hunt, minnows juke to survive.',
    setup: '20×15 yard box. Start: 2 sharks in middle, all others are minnows at one end line. Minnows cross to other side without losing a flag. Tagged minnows become sharks.',
    coachingPoints: [
      'Minnows must get from one end to the other — no camping on the line',
      'Last minnow standing wins that round',
      'Teaches juking under pressure + flag pulling in traffic simultaneously',
      'Great for end of practice — everyone is active every second',
    ],
    playerCount: { min: 5, ideal: 10 },
    equipment: ['cones', 'flags'],
    difficulty: 1,
    isCustom: false,
  },

  // ── DEFENSE ──────────────────────────────────────────────────────────────
  {
    id: 'zone-drop-break',
    name: 'Zone Drop & Break',
    category: 'defense',
    duration: 8,
    description: "5 defenders in zone spots read coach's eyes/arm and break on the ball. 4 receivers run routes. Rotate every 3 plays.",
    setup: 'Full-width zone setup. 4 receivers at positions, 5 defenders in zone spots (think cover 2 or cover 3). Coach plays QB. All 9 kids active.',
    coachingPoints: [
      'Defenders: guard your grass FIRST, then GO when thrown',
      "Read coach's eyes and arm — not the receivers",
      'Quiz the non-targeted receivers: "Where was the open guy?" — forces mental engagement',
      'Rotate offense/defense every 3 plays — everyone plays both sides',
    ],
    playerCount: { min: 6, ideal: 9 },
    equipment: ['footballs', 'cones'],
    difficulty: 2,
    isCustom: false,
  },
  {
    id: 'shark-eyes',
    name: 'Shark Eyes (Two Circles)',
    category: 'defense',
    duration: 5,
    description: "TWO simultaneous circles passing, one defender in each reads eyes and jumps throws. All 9 players active.",
    setup: 'Two circles of 4 kids passing + 1 defender in middle = 10 total. With 9 kids: one circle of 5 + one circle of 4. Both run simultaneously.',
    coachingPoints: [
      "Defender reads thrower's EYES, not the ball — the eyes telegraph the throw",
      'Rotate defender every INT or every 30 seconds',
      'Two circles = ALL kids active simultaneously — no watching',
      'Passers: sell your eyes to a fake receiver, then throw elsewhere',
    ],
    playerCount: { min: 5, ideal: 10 },
    equipment: ['footballs'],
    difficulty: 1,
    isCustom: false,
  },
  {
    id: 'angle-pursuit',
    name: 'Angle Pursuit (Multi-Lane)',
    category: 'defense',
    duration: 5,
    description: 'Defenders take correct pursuit angle to cut off sideline runners. Run 4 pairs simultaneously across the width.',
    setup: 'Set up 4 parallel lanes across the 25-yard width. Runner starts on their sideline, defender starts 5 yards inside. All 4 pairs go simultaneously on signal.',
    coachingPoints: [
      "Don't chase — beat them to the spot ahead of them",
      'Take the correct angle: aim where they\'re GOING, not where they ARE',
      'All 4 pairs go at once — coach watches angles from behind',
      'Swap runner/defender each rep',
    ],
    playerCount: { min: 2, ideal: 10 },
    equipment: ['cones'],
    difficulty: 1,
    isCustom: false,
  },
  {
    id: 'game-interceptor',
    name: 'Game Interceptor',
    category: 'defense',
    duration: 8,
    description: 'Full 5v4 zone defense — QB throws to 4 receivers, 5 defenders read and jump routes from zones. All 9 players active.',
    setup: '4 receivers run short/medium routes from scrimmage line. 5 defenders in zone. Coach or best QB throws. All 9 kids active every play.',
    coachingPoints: [
      'Defenders: eyes on the QB, break when the arm goes forward',
      'Receivers: run crisp routes — lazy routes teach defenders bad habits',
      'Coach defense specifically: "Zone 3, you had that out route — step in front!"',
      'Rotate offense/defense every 3-4 plays',
    ],
    playerCount: { min: 6, ideal: 9 },
    equipment: ['footballs', 'cones'],
    difficulty: 2,
    isCustom: false,
  },
  {
    id: 'shadow-flag-pulling',
    name: 'Shadow Flag Pulling (4v4+)',
    category: 'defense',
    duration: 5,
    description: '4v4 matched pairs in a box — each player tries to grab their assigned opponent\'s flag while protecting their own. All 8 active.',
    setup: '20×15 yard box. 4v4, each player assigned one opponent. Both teams wear flags. On GO, everyone tries to pull their assigned opponent\'s flag.',
    coachingPoints: [
      'Stay with YOUR assigned player — don\'t poach others',
      'Pull their flag while protecting yours — multitask!',
      'Teaches man coverage awareness + flag pulling at speed',
      '9th player rotates in every 45 seconds',
    ],
    playerCount: { min: 4, ideal: 9 },
    equipment: ['cones', 'flags'],
    difficulty: 2,
    isCustom: false,
  },
  {
    id: 'flag-war',
    name: 'Flag War (3v3v3)',
    category: 'defense',
    duration: 6,
    description: '3 teams of 3 simultaneously try to collect the most flags. All 9 players active pulling and protecting.',
    setup: '25×20 yard box. 3 teams of 3 (shirt colors or pinnies). All 9 players have flags. Teams try to pull opponent flags. Count flags collected in 60 seconds. 3 rounds.',
    coachingPoints: [
      'Eyes up — see all threats, not just one person chasing you',
      'Protect your flags by moving — standing still is the worst strategy',
      'Team with most flags after 60 seconds wins the round',
      'Teaches flag pulling under game-speed chaos — best drill for flag technique',
    ],
    playerCount: { min: 6, ideal: 9 },
    equipment: ['cones', 'flags'],
    difficulty: 1,
    isCustom: false,
  },

  // ── ROUTE RUNNING ─────────────────────────────────────────────────────────
  {
    id: 'route-tree-walkthrough',
    name: 'Route Tree Walkthrough (All 9)',
    category: 'routes',
    duration: 8,
    description: 'All 9 players run the same route simultaneously — coach calls route, everyone executes. 0 waiting.',
    setup: 'All 9 players spread across the line of scrimmage 3 yards apart. Coach calls a route (out, curl, go, slant, cross). All 9 run it simultaneously.',
    coachingPoints: [
      'Out route: 5 yards → sharp 90° cut toward sideline — PLANT the outside foot',
      'Curl route: 6 yards → turn back to the QB — find the window',
      'Go route: full sprint — look back at 10 yards',
      'Slant: 3 yards off line → 45° cut across the middle — eyes up through traffic',
      'Cross: run parallel to LOS at 5-6 yard depth',
    ],
    playerCount: { min: 1, ideal: 9 },
    equipment: ['cones'],
    difficulty: 1,
    isCustom: false,
  },
  {
    id: 'two-line-routes',
    name: 'Two-Line Route Running',
    category: 'routes',
    duration: 8,
    description: 'Two simultaneous route lines with two QBs — everyone gets a rep every 30 seconds. The core passing drill.',
    setup: 'Split into 2 groups of 4-5. Two QBs (or coach throws for both with two balls). Both lines run the same route simultaneously to opposite sides.',
    coachingPoints: [
      'Must turn and FIND the ball at the break — eyes to QB',
      'QB delivers on timing — throw before the receiver is fully open',
      'After catching, jog to back of OPPOSITE line (mixes groups)',
      'This IS your passing offense — do it every single practice',
    ],
    playerCount: { min: 4, ideal: 10 },
    equipment: ['footballs'],
    difficulty: 2,
    isCustom: false,
  },
  {
    id: 'four-corner-routes',
    name: 'Four Corner Route Circuit',
    category: 'routes',
    duration: 8,
    description: 'Four stations in corners of a 20×15 area — each corner runs a different route simultaneously. Coach moves to each.',
    setup: 'Mark 4 corners with cones. Corner 1: out routes. Corner 2: curl routes. Corner 3: go routes. Corner 4: slant routes. 2-3 kids per corner. Rotate every 90 sec. Coach throws to each group.',
    coachingPoints: [
      'Focus on the BREAK — sharp cuts, not round loops',
      'Plant the correct foot: outside foot for out/curl, inside foot for slant',
      'Communicate which route you\'re in before snapping',
      'Rotate clockwise every 90 seconds — everyone hits every route',
    ],
    playerCount: { min: 4, ideal: 9 },
    equipment: ['footballs', 'cones'],
    difficulty: 2,
    isCustom: false,
  },
  {
    id: 'crossing-route-catches',
    name: 'Crossing Route Catches',
    category: 'routes',
    duration: 8,
    description: 'Receivers from opposite sides run crossing routes simultaneously — QB leads the throw. Hardest catch for kids, needs the most reps.',
    setup: 'Two lines on opposite ends of a 15-yard span. Coach/QB in center throws timing passes. Both receivers cross simultaneously.',
    coachingPoints: [
      "Eyes on the ball THROUGH the catch — don't look upfield yet",
      'Progress distances: 5 yards → 10 yards → 15 yards',
      'Catches while running laterally are the hardest for kids — this drill fixes it',
      'QB: lead the receiver toward their break direction',
    ],
    playerCount: { min: 3, ideal: 10 },
    equipment: ['footballs', 'cones'],
    difficulty: 2,
    isCustom: false,
  },
  {
    id: 'route-recognition-relay',
    name: 'Route Recognition Relay',
    category: 'routes',
    duration: 7,
    description: 'Coach calls a play, receivers must run their CORRECT assigned routes from memory — tests play recognition while running.',
    setup: 'Full 5-receiver set at the line. Coach calls a play from your actual playbook. Receivers line up and run their assigned routes WITHOUT a huddle walkthrough first.',
    coachingPoints: [
      'Test if they remembered — don\'t re-explain before the snap',
      'After each play: "What route were you supposed to run?" — accountability',
      'Bridges drill time and game time — closest thing to real reps',
      'Start with your 3 most common plays',
    ],
    playerCount: { min: 5, ideal: 9 },
    equipment: ['footballs', 'cones'],
    difficulty: 3,
    isCustom: false,
  },

  // ── RECEIVING ─────────────────────────────────────────────────────────────
  {
    id: 'quick-hands-triangle',
    name: 'Quick Hands Triangle',
    category: 'receiving',
    duration: 5,
    description: 'Groups of 3 in triangles, quick throws — catch and release under 2 seconds. THREE simultaneous triangles for 9 players.',
    setup: 'Groups of 3, triangle formation, 5 yards apart. With 9 kids = 3 triangles all running simultaneously. Add a light defender in the middle after comfortable.',
    coachingPoints: [
      'Catch and release in under 2 seconds — rapid fire',
      'Add a light defender in middle after comfortable with the catch',
      'SOFT hands — don\'t grab, let the ball come to you',
      '3 triangles = all 9 kids getting reps at the same time',
    ],
    playerCount: { min: 3, ideal: 9 },
    equipment: ['footballs'],
    difficulty: 1,
    isCustom: false,
  },
  {
    id: 'nine-player-circuit',
    name: '9-Player Catch Circuit',
    category: 'receiving',
    duration: 8,
    description: 'Three groups of 3 rotate through three catching stations simultaneously — deep ball, short slant, over-the-shoulder.',
    setup: 'Station A (5 yd): quick out catches. Station B (10 yd): crossing catches. Station C (15 yd): go-route deep catches. 3 kids per station, all go simultaneously. Rotate stations every 90 sec.',
    coachingPoints: [
      'Station A: SHORT catches — tuck immediately after catch',
      'Station B: LATERAL catches while running — hardest, needs focus',
      'Station C: DEEP ball — look over your inside shoulder at 12 yards',
      'Coach needs 3 footballs or a helper QB at one station',
    ],
    playerCount: { min: 6, ideal: 9 },
    equipment: ['footballs', 'cones'],
    difficulty: 2,
    isCustom: false,
  },
  {
    id: 'rapid-fire-catch',
    name: 'Rapid Fire Catch',
    category: 'receiving',
    duration: 5,
    description: 'All 9 players line up 8 yards from coach, run routes one right after another in a continuous flow — a catch every 5 seconds.',
    setup: 'All 9 players in a line 8 yards away. Coach throws to each player as they jog across in continuous motion. As soon as ball is caught, next player goes.',
    coachingPoints: [
      'Continuous flow — next kid goes while coach already has next ball ready',
      'Use 2 balls: one in air, one in hand ready',
      'Vary route type: first pass = out, next = cross, next = curl, etc.',
      'Every kid gets a catch every 45 seconds — high reps',
    ],
    playerCount: { min: 3, ideal: 9 },
    equipment: ['footballs'],
    difficulty: 1,
    isCustom: false,
  },

  // ── THROWING ──────────────────────────────────────────────────────────────
  {
    id: 'target-ladder',
    name: 'Target Ladder (Multi-Station)',
    category: 'throwing',
    duration: 5,
    description: '3 throwing stations side-by-side at 5/8/12 yards — all throwers go simultaneously. Track accuracy.',
    setup: '3 parallel stations with receiver cones at 5, 8, 12 yards. 3 kids throwing simultaneously. Must complete 2/3 to "advance." Rotate throwers every 3 reps.',
    coachingPoints: [
      'Must complete 2/3 to advance — keeps it honest',
      'Track accuracy across sessions — progress is motivating',
      '7-second clock means QB must be accurate on short/medium — no deep bombs',
      'Step INTO the throw — plant your front foot toward the target',
    ],
    playerCount: { min: 2, ideal: 9 },
    equipment: ['footballs', 'cones'],
    difficulty: 1,
    isCustom: false,
  },
  {
    id: 'moving-target',
    name: 'Moving Target',
    category: 'throwing',
    duration: 5,
    description: 'QB on the line, all receivers jog across at 8 yards in continuous flow — lead the throw. Continuous for 5 minutes.',
    setup: 'QB on the line (coach). Receivers line up at one side, jog across at 8 yards. As soon as one throw is made, next receiver goes. Use 2 footballs.',
    coachingPoints: [
      'Lead the receiver — hit them in stride ahead of where they ARE',
      'Continuous flow — no breaks between reps',
      'Each kid gets a rep every 15 seconds with 9 players',
      'Teaches timing — the #1 skill gap in youth QBs',
    ],
    playerCount: { min: 3, ideal: 9 },
    equipment: ['footballs'],
    difficulty: 2,
    isCustom: false,
  },
  {
    id: 'qb-rotation-drill',
    name: 'QB Rotation — Everyone Throws',
    category: 'throwing',
    duration: 6,
    description: 'Every kid takes 3 snaps as QB — develops understanding of the position and builds confidence for the whole team.',
    setup: 'Center snaps to rotating QBs. 3-4 receivers run routes. Coach stands next to QB to coach in-ear. Each kid gets 3 throws then rotates to receiver. All 9 rotate through.',
    coachingPoints: [
      'Every kid should try QB — the ones who play other positions will respect it',
      'Keep coaching simple: "Step toward your target. Throw. Good."',
      'Focus on mechanics: grip, stance, follow through',
      'Praise the attempt, correct the mechanics — not the result',
    ],
    playerCount: { min: 3, ideal: 9 },
    equipment: ['footballs'],
    difficulty: 1,
    isCustom: false,
  },

  // ── HANDOFFS ──────────────────────────────────────────────────────────────
  {
    id: 'handoff-circuit',
    name: 'Handoff Circuit (3 Stations)',
    category: 'handoffs',
    duration: 8,
    description: 'Three parallel handoff stations running simultaneously — QB-to-RB handoff timing and ball security. All 9 kids active.',
    setup: '3 stations, 3 kids each (QB, RB, 1 waiting). QB takes snap, RBs run 3 routes: (1) direct handoff left, (2) direct handoff right, (3) fake handoff + QB keeps. All 3 stations go simultaneously.',
    coachingPoints: [
      'RB: make a POCKET with your arms — inside elbow up, outside elbow down',
      'QB: push the ball into the belly pocket firmly, then RIDE it before deciding to give or keep',
      'RB tucks the ball immediately — two hands on it until past the line',
      'Fake handoffs are 50% of the drill — sell the fake!',
    ],
    playerCount: { min: 3, ideal: 9 },
    equipment: ['footballs', 'cones'],
    difficulty: 2,
    isCustom: false,
  },
  {
    id: 'shovel-pass-circuit',
    name: 'Shovel Pass Circuit',
    category: 'handoffs',
    duration: 6,
    description: 'QB shovel-passes to flat receivers simultaneously at all 3 stations. Builds the short game and flag-zone attack.',
    setup: '3 parallel QB-receiver pairs, 5 yards apart. QB snaps, receiver crosses at 3 yards in the flat. QB shovels a quick pass. All 3 pairs go simultaneously.',
    coachingPoints: [
      'Shovel pass: underhanded push-pass to the flat — quick release',
      'Receiver must be moving AWAY from center when they receive it (forward pass rule)',
      'Ball must travel forward — no backward toss (it\'s a pass, not a lateral)',
      'Tuck immediately — it\'s live, there are defenders',
    ],
    playerCount: { min: 3, ideal: 9 },
    equipment: ['footballs', 'cones'],
    difficulty: 2,
    isCustom: false,
  },
  {
    id: 'diamond-handoff',
    name: 'Diamond Formation Handoff',
    category: 'handoffs',
    duration: 6,
    description: 'Full 5-player diamond formation practices handoffs, fakes, and reads. All 9 run through in two waves.',
    setup: 'Line up full diamond: QB, 2 slots, 2 edges. Run 3-4 plays that use handoffs/fakes. Wave 1 (5 kids) runs while wave 2 (4 kids) watches and identifies what each player is doing.',
    coachingPoints: [
      'Wave 2 must watch and be able to explain each player\'s assignment',
      'Focus on the FAKE — if defenders aren\'t fooled, the play doesn\'t work',
      'QB: eyes downfield after the handoff — sell that you kept it',
      'RB: after receiving ball, run NORTH-SOUTH immediately, not sideways',
    ],
    playerCount: { min: 5, ideal: 9 },
    equipment: ['footballs', 'cones'],
    difficulty: 3,
    isCustom: false,
  },

  // ── TEAM ──────────────────────────────────────────────────────────────────
  {
    id: 'play-walkthrough',
    name: 'Offensive Play Drills',
    category: 'team',
    duration: 10,
    description: 'Walk-through/run-through of specific plays from the playbook. All 9 active each rep.',
    setup: 'Full team at line of scrimmage. Walk through at teach speed first, then progress to run speed. 4 on offense (5th rotating), 4 on defense simulating.',
    coachingPoints: [
      'Walk first, then jog, then full speed — in that order every time',
      'Each player must know their assignment BEFORE lining up — ask them',
      'Run each play 3-4 times minimum before moving on',
      'Defense: give realistic coverage, don\'t just stand there',
    ],
    playerCount: { min: 5, ideal: 9 },
    equipment: ['footballs', 'cones'],
    difficulty: 1,
    isCustom: false,
    linkedPlays: true,
  },
  {
    id: 'play-recognition-quiz',
    name: 'Play Recognition Quiz',
    category: 'team',
    duration: 5,
    description: 'Coach points to a player, calls a play — player must describe their assignment from memory before the snap. Tests play knowledge without running.',
    setup: 'All 9 players at scrimmage line. Coach calls a play name. Before they run it, coach points to 2-3 players and asks "What\'s YOUR assignment on this play?" Then they run it.',
    coachingPoints: [
      'Random selection — no warning who will be asked',
      'Wrong answer = play doesn\'t run, they must explain it correctly first',
      'Then run the play and see if they executed what they said',
      'Builds game-speed recall — most important mental skill for this age',
    ],
    playerCount: { min: 5, ideal: 9 },
    equipment: ['footballs', 'cones'],
    difficulty: 2,
    isCustom: false,
    linkedPlays: true,
  },
  {
    id: 'no-huddle-drill',
    name: 'No-Huddle Fast Break',
    category: 'team',
    duration: 8,
    description: 'QB calls play at the line — offense must line up and run in under 10 seconds. Builds communication and game-speed recall.',
    setup: 'Full 5v4 or 5v5. No huddle — QB calls play at line using your play naming system. 10-second play clock. Coach counts it down.',
    coachingPoints: [
      '10-second clock — hustle to the line or it\'s a procedure penalty',
      'QB: loud and clear, use your play names',
      'Other players: confirm your assignment with a nod or thumbs up',
      'Teaches game-speed communication — the hardest soft skill at this age',
    ],
    playerCount: { min: 5, ideal: 9 },
    equipment: ['footballs', 'cones'],
    difficulty: 3,
    isCustom: false,
    linkedPlays: true,
  },
  {
    id: 'cool-down',
    name: 'Cool Down & Team Talk',
    category: 'team',
    duration: 5,
    description: 'Light stretching, recap what we learned, shout-outs, homework reminder. All 9 in a circle.',
    setup: 'Circle up. Light stretches while coach talks. Everyone faces in.',
    coachingPoints: [
      'Recap 1-2 KEY things from today — not everything',
      'Shout out 2-3 specific kids for specific plays they made — names matter',
      'Homework: 10 push-ups, 10 jumping jacks, 10 squats, 2 min jog',
      '"Champions work every day" — end with the team chant',
    ],
    playerCount: { min: 1, ideal: 9 },
    equipment: [],
    difficulty: 1,
    isCustom: false,
  },

  // ── SCRIMMAGE ─────────────────────────────────────────────────────────────
  {
    id: 'scrimmage',
    name: 'Scrimmage',
    category: 'scrimmage',
    duration: 10,
    description: 'Full 5v4 scrimmage — situational or open. 9th player rotates in each series.',
    setup: 'Full field or half field. 5 on offense vs 4 on defense + rotating 9th player. Swap every series.',
    coachingPoints: [
      'Call specific situations: "3rd and long", "red zone", "2-minute drill"',
      'Rotate the 9th player into a key position each series — everyone gets reps',
      'Coach BOTH sides between plays — 15-second coaching window max',
      'Stop and correct but keep it FLOWING — scrimmage is their favorite part',
    ],
    playerCount: { min: 8, ideal: 9 },
    equipment: ['footballs', 'cones', 'flags'],
    difficulty: 1,
    isCustom: false,
  },
  {
    id: 'red-zone-scrimmage',
    name: 'Red Zone Scrimmage',
    category: 'scrimmage',
    duration: 8,
    description: 'Ball starts at the 10-yard line — score or stop in 3 plays. High-pressure situational reps.',
    setup: 'Set up 10-yard red zone. Offense gets 3 plays to score, defense tries to stop. 5v4. Reset after each series, swap offense/defense.',
    coachingPoints: [
      'Red zone = short routes, quick throws — no 20-yard bombs',
      'Defense tightens up — everything is worth more here',
      'Use your 3 best red zone plays from your playbook',
      'Offense: TD or bust — defense: any stop wins',
    ],
    playerCount: { min: 8, ideal: 9 },
    equipment: ['footballs', 'cones', 'flags'],
    difficulty: 2,
    isCustom: false,
  },
  {
    id: 'two-minute-drill',
    name: 'Two-Minute Drill',
    category: 'scrimmage',
    duration: 6,
    description: 'Offense starts at midfield with 2 minutes to score — simulates real game pressure. Tests everything at once.',
    setup: 'Ball at midfield. 2 minutes on the clock. Offense works fast, no-huddle. Defense plays real coverage. Coach tracks clock.',
    coachingPoints: [
      'Offense: hurry to the line after every play — clock is running',
      'QB: check ball placement first, then sprint to line and call play',
      'Focus plays: sideline routes (stop clock), spikes only if desperate',
      'Best learning tool in the game — use it at least once per game-prep week',
    ],
    playerCount: { min: 8, ideal: 9 },
    equipment: ['footballs', 'cones', 'flags'],
    difficulty: 3,
    isCustom: false,
  },
]

export const PRACTICE_TEMPLATES = [
  {
    id: 'template-a',
    name: 'Template A: Evasion + Defense',
    emoji: '🅰️',
    totalMinutes: 60,
    blocks: [
      { drillId: 'dynamic-warmup',     duration: 7,  notes: '', linkedPlays: [] },
      { drillId: 'tag-n-go',           duration: 4,  notes: '', linkedPlays: [] },
      { drillId: 'mirror-dodge',       duration: 5,  notes: '', linkedPlays: [] },
      { drillId: 'gauntlet-run',       duration: 8,  notes: '', linkedPlays: [] },
      { drillId: 'shark-eyes',         duration: 5,  notes: '', linkedPlays: [] },
      { drillId: 'zone-drop-break',    duration: 8,  notes: '', linkedPlays: [] },
      { drillId: 'two-line-routes',    duration: 8,  notes: '', linkedPlays: [] },
      { drillId: 'scrimmage',          duration: 10, notes: '', linkedPlays: [] },
      { drillId: 'cool-down',          duration: 5,  notes: '', linkedPlays: [] },
    ],
  },
  {
    id: 'template-b',
    name: 'Template B: Passing + Receiving',
    emoji: '🅱️',
    totalMinutes: 60,
    blocks: [
      { drillId: 'dynamic-warmup',       duration: 7,  notes: '', linkedPlays: [] },
      { drillId: 'diamond-catch-high',   duration: 2,  notes: '', linkedPlays: [] },
      { drillId: 'pinky-catch-low',      duration: 2,  notes: '', linkedPlays: [] },
      { drillId: 'quick-hands-triangle', duration: 5,  notes: '', linkedPlays: [] },
      { drillId: 'two-line-routes',      duration: 8,  notes: '', linkedPlays: [] },
      { drillId: 'moving-target',        duration: 5,  notes: '', linkedPlays: [] },
      { drillId: 'target-ladder',        duration: 5,  notes: '', linkedPlays: [] },
      { drillId: 'angle-pursuit',        duration: 5,  notes: '', linkedPlays: [] },
      { drillId: 'scrimmage',            duration: 10, notes: '', linkedPlays: [] },
      { drillId: 'cool-down',            duration: 5,  notes: '', linkedPlays: [] },
    ],
  },
  {
    id: 'template-c',
    name: 'Template C: Game Prep',
    emoji: '🅲️',
    totalMinutes: 60,
    blocks: [
      { drillId: 'dynamic-warmup',       duration: 7,  notes: '', linkedPlays: [] },
      { drillId: 'tag-n-go',             duration: 4,  notes: '', linkedPlays: [] },
      { drillId: 'route-tree-walkthrough', duration: 5, notes: '', linkedPlays: [] },
      { drillId: 'play-walkthrough',     duration: 10, notes: '', linkedPlays: [] },
      { drillId: 'zone-drop-break',      duration: 8,  notes: '', linkedPlays: [] },
      { drillId: 'no-huddle-drill',      duration: 6,  notes: '', linkedPlays: [] },
      { drillId: 'red-zone-scrimmage',   duration: 8,  notes: '', linkedPlays: [] },
      { drillId: 'cool-down',            duration: 5,  notes: '', linkedPlays: [] },
    ],
  },
  {
    id: 'template-d',
    name: 'Template D: Handoffs + Routes',
    emoji: '🅳',
    totalMinutes: 60,
    blocks: [
      { drillId: 'dynamic-warmup',       duration: 7,  notes: '', linkedPlays: [] },
      { drillId: 'defensive-shuffle',    duration: 3,  notes: '', linkedPlays: [] },
      { drillId: 'handoff-circuit',      duration: 8,  notes: '', linkedPlays: [] },
      { drillId: 'four-corner-routes',   duration: 8,  notes: '', linkedPlays: [] },
      { drillId: 'shovel-pass-circuit',  duration: 6,  notes: '', linkedPlays: [] },
      { drillId: 'game-interceptor',     duration: 8,  notes: '', linkedPlays: [] },
      { drillId: 'scrimmage',            duration: 10, notes: '', linkedPlays: [] },
      { drillId: 'cool-down',            duration: 5,  notes: '', linkedPlays: [] },
    ],
  },
]

// ── Helpers ───────────────────────────────────────────────────────────────

/**
 * Get a drill by ID (includes custom drills passed in).
 * @param {string} id
 * @param {Array} [customDrills=[]]
 * @returns {Object|undefined}
 */
export function getDrillById(id, customDrills = []) {
  return DRILL_LIBRARY.find(d => d.id === id) || customDrills.find(d => d.id === id)
}

/**
 * Get all drills in a category.
 * @param {string} cat - Category key or '' for all
 * @param {Array} [customDrills=[]]
 * @returns {Array}
 */
export function getDrillsByCategory(cat, customDrills = []) {
  const all = [...DRILL_LIBRARY, ...customDrills]
  if (!cat) return all
  return all.filter(d => d.category === cat)
}

/**
 * Filter drills by search string.
 * @param {string} search
 * @param {string} [cat='']
 * @param {Array} [customDrills=[]]
 * @returns {Array}
 */
export function filterDrills(search, cat = '', customDrills = []) {
  const all = getDrillsByCategory(cat, customDrills)
  if (!search) return all
  const q = search.toLowerCase()
  return all.filter(d =>
    d.name.toLowerCase().includes(q) ||
    d.description.toLowerCase().includes(q) ||
    d.category.toLowerCase().includes(q)
  )
}
