// juke-data.js — Juke move data for animation tutorials
// 6 moves with step-by-step footprint data, coaching cues, and biomechanics

export const JUKE_METADATA = {
  coordinateSystem: {
    yAxis: 'forward',
    xAxis: 'lateral',
    units: 'inches',
    strideRange: '18-24 inches for youth players',
  },
  angleConventions: {
    zero: 'straight ahead (forward)',
    positive: 'clockwise from forward',
    negative: 'counter-clockwise from forward',
  },
}

export const JUKE_MOVES = [
  // ── 1. Cut / Juke ─────────────────────────────────────────────────────────
  {
    id: 'cut-juke',
    name: 'Cut / Juke',
    description: 'Head and shoulder fake one direction, plant outside foot hard, cut the other way.',
    totalSteps: 6,
    approachDirection: 'forward',
    exitDirection: '45-degrees-right',
    phases: [
      {
        phase: 'approach',
        description: 'Running forward at the defender',
        steps: [
          {
            stepNumber: 1,
            foot: 'right',
            position: { x: 2, y: 0 },
            angle: 0,
            action: 'stride',
            weight: 0.5,
            duration: 0.15,
            teachDuration: 0.8,
            emphasis: false,
            armPosition: 'normal running motion',
            headDirection: 'eyes on defender',
            forceVector: { angle: 0, magnitude: 0.5 },
          },
          {
            stepNumber: 2,
            foot: 'left',
            position: { x: -2, y: 20 },
            angle: 0,
            action: 'stride',
            weight: 0.5,
            duration: 0.15,
            teachDuration: 0.8,
            emphasis: false,
            armPosition: 'normal running motion',
            headDirection: 'eyes on defender',
            forceVector: { angle: 0, magnitude: 0.5 },
          },
        ],
      },
      {
        phase: 'fake',
        description: 'Sell the fake — head and shoulders lean LEFT',
        steps: [
          {
            stepNumber: 3,
            foot: 'right',
            position: { x: -6, y: 38 },
            angle: -20,
            action: 'stride',
            weight: 0.4,
            duration: 0.15,
            teachDuration: 1.0,
            emphasis: true,
            armPosition: 'left arm reaches left, selling the fake',
            headDirection: 'look LEFT — sell it!',
            shoulderFake: 'dip left shoulder hard',
            forceVector: { angle: -30, magnitude: 0.4 },
          },
        ],
      },
      {
        phase: 'plant',
        description: 'Plant the LEFT foot HARD — this is the power foot',
        steps: [
          {
            stepNumber: 4,
            foot: 'left',
            position: { x: -8, y: 48 },
            angle: -10,
            action: 'plant',
            weight: 0.95,
            duration: 0.12,
            teachDuration: 1.2,
            emphasis: true,
            armPosition: 'arms ready to drive right',
            headDirection: 'snap head RIGHT — where you want to go',
            forceVector: { angle: 135, magnitude: 0.9 },
          },
        ],
      },
      {
        phase: 'cut',
        description: 'Explode RIGHT off the plant foot',
        steps: [
          {
            stepNumber: 5,
            foot: 'right',
            position: { x: 6, y: 56 },
            angle: 40,
            action: 'push-off',
            weight: 0.7,
            duration: 0.1,
            teachDuration: 0.8,
            emphasis: true,
            armPosition: 'right arm pumps forward, driving the cut',
            headDirection: 'eyes upfield right',
            forceVector: { angle: 45, magnitude: 0.8 },
          },
        ],
      },
      {
        phase: 'acceleration',
        description: 'Sprint away at 45 degrees right',
        steps: [
          {
            stepNumber: 6,
            foot: 'left',
            position: { x: 16, y: 68 },
            angle: 40,
            action: 'stride',
            weight: 0.5,
            duration: 0.12,
            teachDuration: 0.6,
            emphasis: false,
            armPosition: 'full sprint arm pump',
            headDirection: 'eyes downfield — GO!',
            forceVector: { angle: 45, magnitude: 0.7 },
          },
        ],
      },
    ],
    coachingCues: [
      'Sell the fake with your HEAD and SHOULDERS, not just your feet',
      'Plant foot needs to be OUTSIDE foot (left foot to go right)',
      'Low center of gravity — bend those knees!',
      'The faster you plant, the faster you cut',
      'Eyes sell the move — look where you fake, then snap to where you go',
    ],
    commonMistakes: [
      'Not selling the fake — just stepping sideways without the shoulder dip',
      'Standing too tall — high center of gravity means slow cuts',
      'Planting with the wrong foot (inside instead of outside)',
      'Slowing down too much before the cut — maintain speed through the move',
      'Looking at the ground instead of the defender',
    ],
  },

  // ── 2. Drop ────────────────────────────────────────────────────────────────
  {
    id: 'drop',
    name: 'Drop',
    description: 'Dead leg drag to freeze the defender, then redirect and accelerate.',
    totalSteps: 5,
    approachDirection: 'forward',
    exitDirection: '30-degrees-left',
    phases: [
      {
        phase: 'approach',
        description: 'Running forward at moderate speed',
        steps: [
          {
            stepNumber: 1,
            foot: 'right',
            position: { x: 2, y: 0 },
            angle: 0,
            action: 'stride',
            weight: 0.5,
            duration: 0.15,
            teachDuration: 0.8,
            emphasis: false,
            armPosition: 'normal running motion',
            headDirection: 'eyes on defender',
            forceVector: { angle: 0, magnitude: 0.5 },
          },
        ],
      },
      {
        phase: 'drop',
        description: 'Drag the right foot — "dead leg" to freeze defender',
        steps: [
          {
            stepNumber: 2,
            foot: 'left',
            position: { x: -2, y: 18 },
            angle: 0,
            action: 'plant',
            weight: 0.85,
            duration: 0.2,
            teachDuration: 1.2,
            emphasis: true,
            armPosition: 'right arm drops, shoulder dips right',
            headDirection: 'slight head fake right',
            shoulderFake: 'right shoulder drops down',
            forceVector: { angle: 0, magnitude: 0.3 },
          },
          {
            stepNumber: 3,
            foot: 'right',
            position: { x: 4, y: 22 },
            angle: 10,
            action: 'drag',
            weight: 0.15,
            duration: 0.25,
            teachDuration: 1.0,
            emphasis: true,
            armPosition: 'arms low, body compact',
            headDirection: 'eyes still on defender — selling the freeze',
            forceVector: { angle: 0, magnitude: 0.1 },
          },
        ],
      },
      {
        phase: 'redirect',
        description: 'Push off the planted left foot, redirect LEFT',
        steps: [
          {
            stepNumber: 4,
            foot: 'left',
            position: { x: -6, y: 34 },
            angle: -25,
            action: 'push-off',
            weight: 0.8,
            duration: 0.12,
            teachDuration: 0.8,
            emphasis: true,
            armPosition: 'left arm drives forward',
            headDirection: 'snap head left — GO',
            forceVector: { angle: -30, magnitude: 0.8 },
          },
        ],
      },
      {
        phase: 'acceleration',
        description: 'Sprint away at 30 degrees left',
        steps: [
          {
            stepNumber: 5,
            foot: 'right',
            position: { x: -14, y: 48 },
            angle: -25,
            action: 'stride',
            weight: 0.5,
            duration: 0.12,
            teachDuration: 0.6,
            emphasis: false,
            armPosition: 'full sprint arms',
            headDirection: 'eyes downfield',
            forceVector: { angle: -30, magnitude: 0.7 },
          },
        ],
      },
    ],
    coachingCues: [
      'The "dead leg" drag is what freezes the defender',
      'Drop your shoulder on the drag side — make it look like you\'re falling',
      'Keep weight on the PLANT foot (left) — the drag foot barely touches',
      'Quick redirect — don\'t hang in the drop too long',
      'Think: plant, drag, EXPLODE',
    ],
    commonMistakes: [
      'Putting weight on the drag foot — it should be "dead"',
      'Not dipping the shoulder — the drop looks fake without it',
      'Stopping completely — you should slow, not stop',
      'Redirecting too slowly after the freeze',
      'Dragging for too long — 1 count maximum',
    ],
  },

  // ── 3. Get Skinny ──────────────────────────────────────────────────────────
  {
    id: 'get-skinny',
    name: 'Get Skinny',
    description: 'Turn your body sideways to slip through a narrow gap between defenders.',
    totalSteps: 5,
    approachDirection: 'forward',
    exitDirection: 'forward',
    phases: [
      {
        phase: 'approach',
        description: 'Running forward toward the gap',
        steps: [
          {
            stepNumber: 1,
            foot: 'right',
            position: { x: 2, y: 0 },
            angle: 0,
            action: 'stride',
            weight: 0.5,
            duration: 0.15,
            teachDuration: 0.8,
            emphasis: false,
            armPosition: 'normal running',
            headDirection: 'eyes scanning for the gap',
            forceVector: { angle: 0, magnitude: 0.5 },
          },
        ],
      },
      {
        phase: 'rotate',
        description: 'Turn sideways — make yourself THIN',
        steps: [
          {
            stepNumber: 2,
            foot: 'left',
            position: { x: -1, y: 18 },
            angle: 80,
            action: 'pivot',
            weight: 0.7,
            duration: 0.15,
            teachDuration: 1.0,
            emphasis: true,
            armPosition: 'tuck ball tight to chest, elbows in',
            headDirection: 'turn head sideways, eyes forward through gap',
            forceVector: { angle: 0, magnitude: 0.4 },
          },
          {
            stepNumber: 3,
            foot: 'right',
            position: { x: 1, y: 30 },
            angle: 80,
            action: 'shuffle',
            weight: 0.5,
            duration: 0.15,
            teachDuration: 0.8,
            emphasis: true,
            armPosition: 'ball tucked tight — protect it!',
            headDirection: 'eyes through the gap',
            forceVector: { angle: 0, magnitude: 0.5 },
          },
        ],
      },
      {
        phase: 'slip-through',
        description: 'Slide through the gap sideways',
        steps: [
          {
            stepNumber: 4,
            foot: 'left',
            position: { x: -1, y: 42 },
            angle: 45,
            action: 'slide',
            weight: 0.6,
            duration: 0.12,
            teachDuration: 0.8,
            emphasis: false,
            armPosition: 'ball protected, body rotating back forward',
            headDirection: 'eyes forward, through the gap',
            forceVector: { angle: 0, magnitude: 0.6 },
          },
        ],
      },
      {
        phase: 'acceleration',
        description: 'Rotate back to forward and accelerate',
        steps: [
          {
            stepNumber: 5,
            foot: 'right',
            position: { x: 2, y: 56 },
            angle: 10,
            action: 'stride',
            weight: 0.5,
            duration: 0.12,
            teachDuration: 0.6,
            emphasis: false,
            armPosition: 'back to sprint arms',
            headDirection: 'eyes downfield — GO!',
            forceVector: { angle: 0, magnitude: 0.7 },
          },
        ],
      },
    ],
    coachingCues: [
      'Tuck the ball TIGHT — this is a fumble-risk move',
      'Turn your body 90 degrees — shoulders perpendicular to the gap',
      'Keep your speed UP — don\'t slow down to get skinny',
      'This works best in traffic near the line of scrimmage',
      'Quick rotation back to forward after slipping through',
    ],
    commonMistakes: [
      'Loose ball — must be tucked tight with both hands',
      'Slowing down too much — momentum is what carries you through',
      'Not rotating enough — still presenting a wide profile',
      'Forgetting to rotate BACK to forward after the gap',
      'Using this in open field (it\'s a traffic move, not open field)',
    ],
  },

  // ── 4. Speed Change ────────────────────────────────────────────────────────
  {
    id: 'speed-change',
    name: 'Speed Change',
    description: 'Decelerate to a shuffle, freeze the defender, then explode to full speed.',
    totalSteps: 6,
    approachDirection: 'forward',
    exitDirection: 'forward',
    phases: [
      {
        phase: 'approach',
        description: 'Running forward at 80% speed',
        steps: [
          {
            stepNumber: 1,
            foot: 'right',
            position: { x: 2, y: 0 },
            angle: 0,
            action: 'stride',
            weight: 0.5,
            duration: 0.12,
            teachDuration: 0.6,
            emphasis: false,
            armPosition: 'normal running',
            headDirection: 'eyes on defender',
            forceVector: { angle: 0, magnitude: 0.6 },
          },
          {
            stepNumber: 2,
            foot: 'left',
            position: { x: -2, y: 20 },
            angle: 0,
            action: 'stride',
            weight: 0.5,
            duration: 0.12,
            teachDuration: 0.6,
            emphasis: false,
            armPosition: 'normal running',
            headDirection: 'eyes on defender',
            forceVector: { angle: 0, magnitude: 0.6 },
          },
        ],
      },
      {
        phase: 'deceleration',
        description: 'Quick choppy steps — SLOW DOWN dramatically',
        steps: [
          {
            stepNumber: 3,
            foot: 'right',
            position: { x: 1, y: 30 },
            angle: 0,
            action: 'shuffle',
            weight: 0.5,
            duration: 0.2,
            teachDuration: 1.0,
            emphasis: true,
            armPosition: 'arms come down, body lowers',
            headDirection: 'look casual — sell the slowdown',
            forceVector: { angle: 180, magnitude: 0.3 },
          },
          {
            stepNumber: 4,
            foot: 'left',
            position: { x: -1, y: 34 },
            angle: 0,
            action: 'shuffle',
            weight: 0.5,
            duration: 0.2,
            teachDuration: 1.0,
            emphasis: true,
            armPosition: 'arms relaxed — fake like you\'re done',
            headDirection: 'head up but relaxed',
            forceVector: { angle: 180, magnitude: 0.2 },
          },
        ],
      },
      {
        phase: 'explosion',
        description: 'EXPLODE forward — 0 to 100!',
        steps: [
          {
            stepNumber: 5,
            foot: 'right',
            position: { x: 2, y: 46 },
            angle: 0,
            action: 'push-off',
            weight: 0.8,
            duration: 0.1,
            teachDuration: 0.8,
            emphasis: true,
            armPosition: 'PUMP those arms — max effort',
            headDirection: 'eyes downfield, lean forward',
            forceVector: { angle: 0, magnitude: 0.9 },
          },
          {
            stepNumber: 6,
            foot: 'left',
            position: { x: -2, y: 64 },
            angle: 0,
            action: 'stride',
            weight: 0.5,
            duration: 0.1,
            teachDuration: 0.6,
            emphasis: false,
            armPosition: 'full sprint',
            headDirection: 'eyes downfield — GONE!',
            forceVector: { angle: 0, magnitude: 0.8 },
          },
        ],
      },
    ],
    coachingCues: [
      'The bigger the speed DIFFERENCE, the more effective the move',
      'Sell the slowdown — look like you\'re jogging, then EXPLODE',
      'Choppy feet during deceleration (buzz steps)',
      'Forward lean on the explosion — like a sprinter out of blocks',
      'This is the easiest move to learn and the hardest to defend',
    ],
    commonMistakes: [
      'Not slowing down enough — defender doesn\'t bite',
      'Slowing down for too long — gives defender time to recover',
      'Not exploding hard enough — the burst needs to be dramatic',
      'Telegraphing the explosion with your arms before your feet move',
      'Using this too far from the defender (need to be within 5 yards)',
    ],
  },

  // ── 5. Shimmy ──────────────────────────────────────────────────────────────
  {
    id: 'shimmy',
    name: 'Shimmy',
    description: 'Rapid side-to-side shuffles to freeze the defender, then burst past.',
    totalSteps: 7,
    approachDirection: 'forward',
    exitDirection: '30-degrees-right',
    phases: [
      {
        phase: 'approach',
        description: 'Running forward, slowing slightly',
        steps: [
          {
            stepNumber: 1,
            foot: 'right',
            position: { x: 2, y: 0 },
            angle: 0,
            action: 'stride',
            weight: 0.5,
            duration: 0.15,
            teachDuration: 0.7,
            emphasis: false,
            armPosition: 'normal running',
            headDirection: 'eyes on defender',
            forceVector: { angle: 0, magnitude: 0.5 },
          },
        ],
      },
      {
        phase: 'shimmy',
        description: 'Quick side-to-side — LEFT, RIGHT, LEFT',
        steps: [
          {
            stepNumber: 2,
            foot: 'left',
            position: { x: -8, y: 16 },
            angle: -15,
            action: 'shuffle',
            weight: 0.5,
            duration: 0.1,
            teachDuration: 0.7,
            emphasis: true,
            armPosition: 'arms wide for balance',
            headDirection: 'fake look left',
            forceVector: { angle: -90, magnitude: 0.4 },
          },
          {
            stepNumber: 3,
            foot: 'right',
            position: { x: 8, y: 22 },
            angle: 15,
            action: 'shuffle',
            weight: 0.5,
            duration: 0.1,
            teachDuration: 0.7,
            emphasis: true,
            armPosition: 'arms swing right',
            headDirection: 'fake look right',
            forceVector: { angle: 90, magnitude: 0.4 },
          },
          {
            stepNumber: 4,
            foot: 'left',
            position: { x: -6, y: 28 },
            angle: -10,
            action: 'shuffle',
            weight: 0.5,
            duration: 0.1,
            teachDuration: 0.7,
            emphasis: true,
            armPosition: 'arms swing left',
            headDirection: 'eyes on defender hips',
            forceVector: { angle: -90, magnitude: 0.4 },
          },
          {
            stepNumber: 5,
            foot: 'right',
            position: { x: 4, y: 34 },
            angle: 10,
            action: 'plant',
            weight: 0.85,
            duration: 0.12,
            teachDuration: 0.8,
            emphasis: true,
            armPosition: 'arms ready to drive',
            headDirection: 'pick your lane — commit!',
            forceVector: { angle: 45, magnitude: 0.6 },
          },
        ],
      },
      {
        phase: 'burst',
        description: 'Pick a lane and BURST past the frozen defender',
        steps: [
          {
            stepNumber: 6,
            foot: 'left',
            position: { x: -2, y: 46 },
            angle: 20,
            action: 'push-off',
            weight: 0.7,
            duration: 0.1,
            teachDuration: 0.6,
            emphasis: false,
            armPosition: 'sprint arms engaged',
            headDirection: 'eyes through the gap',
            forceVector: { angle: 30, magnitude: 0.8 },
          },
          {
            stepNumber: 7,
            foot: 'right',
            position: { x: 8, y: 60 },
            angle: 25,
            action: 'stride',
            weight: 0.5,
            duration: 0.1,
            teachDuration: 0.6,
            emphasis: false,
            armPosition: 'full sprint',
            headDirection: 'eyes downfield',
            forceVector: { angle: 30, magnitude: 0.7 },
          },
        ],
      },
    ],
    coachingCues: [
      'The shimmy is about SPEED of the side-to-side, not distance',
      'Keep feet close to the ground — no hopping!',
      'Watch the defender\'s HIPS — when they shift, burst the other way',
      'Stay low through the whole shimmy — knees bent',
      '3 shimmies max — more than that and you lose speed',
    ],
    commonMistakes: [
      'Too wide — shuffling 3+ yards sideways wastes time',
      'Too many shimmies — 2-3 is enough, then GO',
      'Standing upright — need to stay low and athletic',
      'Not watching the defender — shimmy with no read is just dancing',
      'Hopping instead of shuffling — feet stay close to the ground',
    ],
  },

  // ── 6. Spin ────────────────────────────────────────────────────────────────
  {
    id: 'spin',
    name: 'Spin',
    description: '360-degree spin pivot to avoid a defender at close range.',
    totalSteps: 5,
    approachDirection: 'forward',
    exitDirection: 'forward-right',
    phases: [
      {
        phase: 'approach',
        description: 'Running toward the defender at controlled speed',
        steps: [
          {
            stepNumber: 1,
            foot: 'right',
            position: { x: 2, y: 0 },
            angle: 0,
            action: 'stride',
            weight: 0.5,
            duration: 0.15,
            teachDuration: 0.8,
            emphasis: false,
            armPosition: 'normal running',
            headDirection: 'eyes on defender',
            forceVector: { angle: 0, magnitude: 0.5 },
          },
        ],
      },
      {
        phase: 'plant',
        description: 'Plant the LEFT foot — this is your spin axis',
        steps: [
          {
            stepNumber: 2,
            foot: 'left',
            position: { x: -2, y: 20 },
            angle: 0,
            action: 'plant',
            weight: 0.9,
            duration: 0.12,
            teachDuration: 1.0,
            emphasis: true,
            armPosition: 'ball tucked tight in RIGHT arm, left arm out for balance',
            headDirection: 'head starts turning RIGHT (direction of spin)',
            forceVector: { angle: 0, magnitude: 0.3 },
          },
        ],
      },
      {
        phase: 'spin',
        description: '360° spin on the left foot — FAST!',
        steps: [
          {
            stepNumber: 3,
            foot: 'right',
            position: { x: 4, y: 24 },
            angle: 180,
            action: 'pivot',
            weight: 0.2,
            duration: 0.2,
            teachDuration: 1.2,
            emphasis: true,
            armPosition: 'ball tucked, elbows tight — protect the ball!',
            headDirection: 'head leads the spin — look where you\'re going',
            forceVector: { angle: 90, magnitude: 0.3 },
          },
          {
            stepNumber: 4,
            foot: 'left',
            position: { x: -2, y: 28 },
            angle: 350,
            action: 'pivot',
            weight: 0.7,
            duration: 0.15,
            teachDuration: 1.0,
            emphasis: true,
            armPosition: 'ball secure, completing the rotation',
            headDirection: 'eyes coming back to forward — find your lane',
            forceVector: { angle: 0, magnitude: 0.5 },
          },
        ],
      },
      {
        phase: 'acceleration',
        description: 'Exit the spin and accelerate',
        steps: [
          {
            stepNumber: 5,
            foot: 'right',
            position: { x: 6, y: 42 },
            angle: 15,
            action: 'push-off',
            weight: 0.7,
            duration: 0.1,
            teachDuration: 0.6,
            emphasis: false,
            armPosition: 'sprint arms — GO!',
            headDirection: 'eyes downfield',
            forceVector: { angle: 15, magnitude: 0.8 },
          },
        ],
      },
    ],
    coachingCues: [
      'TUCK THE BALL — #1 rule of the spin. Switch to outside arm if needed.',
      'Head leads the spin — your body follows where you look',
      'Plant foot stays on the ground — spin on the ball of your foot',
      'Stay LOW through the spin — don\'t pop up',
      'This is a CLOSE RANGE move — use within 2 yards of the defender',
      'Practice spinning BOTH directions',
    ],
    commonMistakes: [
      'Loose ball — the spin is the #1 fumble-risk move in football',
      'Spinning too early (too far from defender) — they just follow you around',
      'Spinning too slowly — the move must be quick or the defender grabs you mid-spin',
      'Popping up during the spin — stay low for balance',
      'Not accelerating out of the spin — many kids spin and then jog',
      'Only spinning one direction — defenders learn to anticipate',
    ],
  },
]

// ── Helper functions ──────────────────────────────────────────────────────

export function getJukeMove(id) {
  return JUKE_MOVES.find(m => m.id === id)
}

export function getAllSteps(move) {
  return move.phases.flatMap(p => p.steps)
}

export function getPhaseForStep(move, stepNumber) {
  for (const phase of move.phases) {
    if (phase.steps.some(s => s.stepNumber === stepNumber)) {
      return phase
    }
  }
  return null
}
